export const initialCards = [
  {
    id: 1,
    title: 'Стул серый',
    img: 'chair.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    category: 'chairs',
    price: '450.99',
  },
  {
    id: 2,
    title: 'Стул белый',
    img: 'chair2.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    category: 'chairs',
    price: '145.99',
  },
  {
    id: 3,
    title: 'Стол',
    img: 'table.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    category: 'tables',
    price: '745.99',
  },
  {
    id: 4,
    title: 'Стул серый',
    img: 'chair.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    category: 'chairs',
    price: '340.99',
  },
  {
    id: 5,
    title: 'Стул белый',
    img: 'chair2.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    category: 'chairs',
    price: '120.99',
  },
  {
    id: 6,
    title: 'Стол',
    img: 'table.jpg',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    category: 'chairs',
    price: '899.99',
  },
  {
    id: 7,
    title: 'Диван',
    img: 'sofa.png',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    category: 'sofa',
    price: '250.50',
  },
  {
    id: 8,
    title: 'Светильник',
    img: 'luminaire.jpeg',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    category: 'luminaires',
    price: '780',
  },
  {
    id: 9,
    title: 'Светильник',
    img: 'luminaire2.jpeg',
    desc: 'Lorem ipsum dolor sit amet consectetur adipisicing elit.',
    category: 'luminaires',
    price: '344',
  }
]